name: Update Go Modules

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-go-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Generate go.sum and tidy modules
        run: |
          go mod tidy

      - name: Commit and push if go.sum changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          if [ -n "$(git status --porcelain | grep 'go.sum')" ]; then
            git add go.mod go.sum
            git commit -m "chore: update go.mod and go.sum by GitHub Actions"
            git push
          else
            echo "No go.mod or go.sum changes detected"
          fi
